"""Tool services: image generation and presentation (PPT/PDF) generation."""
import base64
import re
from pathlib import Path
from typing import List
from uuid import uuid4

import httpx
from fastapi import HTTPException

from app.config import get_settings
from app.services.ai_service import ai_service


async def _save_image_bytes(data: bytes, settings) -> str:
    folder = settings.generated_dir / "images"
    folder.mkdir(parents=True, exist_ok=True)
    fname = uuid4().hex + ".png"
    (folder / fname).write_bytes(data)
    return "/static/generated/images/" + fname


async def _generate_image_openai(prompt: str, api_key: str) -> bytes:
    """Generate an image via OpenAI's images API (DALL·E). Returns raw PNG bytes."""
    settings = get_settings()
    base = (settings.image_gen_base_url or "https://api.openai.com/v1").rstrip("/")
    url = base + "/images/generations"
    headers = {
        "Authorization": "Bearer " + api_key,
        "Content-Type": "application/json",
    }
    # Try the common models in order; first that works wins.
    last_err = "no models attempted"
    for model in ("dall-e-3", "gpt-image-1", "dall-e-2"):
        try:
            async with httpx.AsyncClient(timeout=120) as client:
                resp = await client.post(
                    url,
                    headers=headers,
                    json={
                        "model": model,
                        "prompt": prompt,
                        "n": 1,
                        "size": "1024x1024",
                        "response_format": "b64_json",
                    },
                )
                if resp.status_code != 200:
                    last_err = f"{model} -> HTTP {resp.status_code}: {resp.text[:200]}"
                    continue
                b64 = resp.json()["data"][0]["b64_json"]
                return base64.b64decode(b64)
        except Exception as e:
            last_err = f"{model} -> {e}"
            continue
    raise RuntimeError(last_err)


async def generate_image(prompt: str) -> str:
    """Generate an image and store it locally, returning its static URL.

    Uses OpenAI's image API when a key is available (IMAGE_GENERATION_API_KEY,
    falling back to VISION_API_KEY). Otherwise falls back to Pollinations.
    """
    settings = get_settings()
    prompt = (prompt or "").strip()
    if not prompt:
        raise HTTPException(status_code=400, detail="Image prompt is required.")

    api_key = settings.image_gen_api_key or settings.vision_api_key
    if api_key:
        try:
            data = await _generate_image_openai(prompt, api_key)
            return await _save_image_bytes(data, settings)
        except Exception as e:
            raise HTTPException(
                status_code=502,
                detail="Image generation failed: " + str(e)[:160],
            )

    # No key: best-effort Pollinations (works where DNS resolves).
    url = (
        "https://image.pollinations.xyz/"
        + re.sub(r"\s+", "-", prompt)[:1200]
        + "?width=1024&height=1024&nologo=true&model=flux&enhance=true"
    )
    try:
        async with httpx.AsyncClient(timeout=120, follow_redirects=True) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            data = resp.content
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail="Image generation failed (upstream unavailable). " + str(e)[:120],
        )
    return await _save_image_bytes(data, settings)


def _build_pptx(out_path: Path, title: str, slides: List[dict]):
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]

    accent = RGBColor(0x63, 0x66, 0xF1)

    # Title slide
    s = prs.slides.add_slide(blank)
    box = s.shapes.add_textbox(Inches(0.8), Inches(2.6), Inches(11.7), Inches(2.2))
    tf = box.text_frame
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    run = p.add_run(); run.text = title
    run.font.size = Pt(44); run.font.bold = True; run.font.color.rgb = accent
    sub = s.shapes.add_textbox(Inches(0.8), Inches(4.6), Inches(11.7), Inches(0.8))
    sp = sub.text_frame.paragraphs[0]; sp.alignment = PP_ALIGN.CENTER
    sr = sp.add_run(); sr.text = "Generated by Spike"
    sr.font.size = Pt(16); sr.font.color.rgb = RGBColor(0x6B, 0x68, 0x85)

    for slide in slides:
        s = prs.slides.add_slide(blank)
        # Heading band
        band = s.shapes.add_textbox(Inches(0.6), Inches(0.5), Inches(12.1), Inches(1.1))
        hf = band.text_frame; hp = hf.paragraphs[0]
        hr = hp.add_run(); hr.text = slide.get("title", "")
        hr.font.size = Pt(30); hr.font.bold = True; hr.font.color.rgb = accent
        # Bullets
        body = s.shapes.add_textbox(Inches(0.9), Inches(1.9), Inches(11.5), Inches(5.0))
        bf = body.text_frame; bf.word_wrap = True
        first = True
        for b in slide.get("bullets", [])[:6]:
            para = bf.paragraphs[0] if first else bf.add_paragraph()
            first = False
            para.space_after = Pt(10)
            r = para.add_run(); r.text = "•  " + str(b)
            r.font.size = Pt(20); r.font.color.rgb = RGBColor(0x1C, 0x1A, 0x2E)

    prs.save(out_path)


def _build_pdf(out_path: Path, title: str, slides: List[dict]):
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

    doc = SimpleDocTemplate(
        str(out_path), pagesize=letter,
        leftMargin=0.9 * inch, rightMargin=0.9 * inch,
        topMargin=0.9 * inch, bottomMargin=0.9 * inch,
    )
    styles = getSampleStyleSheet()
    h = ParagraphStyle("H", parent=styles["Title"], textColor=colors.HexColor("#6366F1"),
                       fontSize=26, spaceAfter=14)
    b = ParagraphStyle("B", parent=styles["BodyText"], fontSize=15, leading=22,
                       spaceAfter=8)
    flow = [Paragraph(title, h), Spacer(1, 6)]
    for slide in slides:
        flow.append(Paragraph(slide.get("title", ""), ParagraphStyle(
            "S", parent=styles["Heading2"], textColor=colors.HexColor("#4F46E5"))))
        for item in slide.get("bullets", [])[:6]:
            flow.append(Paragraph("• " + str(item), b))
        flow.append(Spacer(1, 12))
    doc.build(flow)


async def generate_ppt(topic: str, slides: int = 6) -> dict:
    """Generate a .pptx and a .pdf for a topic. Returns download URLs + title."""
    topic = (topic or "").strip()
    if not topic:
        raise HTTPException(status_code=400, detail="Presentation topic is required.")

    outline = await ai_service.outline_presentation(topic, slides=slides)
    title = outline[0].get("title", topic) if outline else topic
    # Ensure a clean presentation title (use topic if first slide is generic)
    if not outline:
        raise HTTPException(status_code=500, detail="Could not plan the presentation.")

    settings = get_settings()
    folder = settings.generated_dir / "ppt"
    folder.mkdir(parents=True, exist_ok=True)
    uid = uuid4().hex
    pptx_path = folder / (uid + ".pptx")
    pdf_path = folder / (uid + ".pdf")

    _build_pptx(pptx_path, title, outline)
    try:
        _build_pdf(pdf_path, title, outline)
    except Exception:
        # PDF is a bonus; if it fails we still return the PPTX.
        pdf_path = None

    return {
        "title": title,
        "pptx": "/static/generated/ppt/" + pptx_path.name,
        "pdf": ("/static/generated/ppt/" + pdf_path.name) if pdf_path else None,
        "slides": len(outline),
    }
